name: Build HomeProxy APK

on:
  workflow_dispatch:

  push:
    branches:
      - master
      - dev
    paths:
      - 'htdocs/**'
      - 'po/**'
      - 'root/**'
      - 'Makefile'
      - '.github/**'

  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v5

      - name: Build APK
        run: |
          set -e

          chmod +x .github/build-apk.sh

          .github/build-apk.sh

      - name: Show APK
        run: |
          echo "===== APK ====="
          find .github/output \
            -type f \
            -name "*.apk" \
            -print

          ls -lah .github/output/

      - name: Upload Artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: homeproxy-apk
          path: .github/output/*.apk
          if-no-files-found: error

      - name: Upload APK to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file: .github/output/*.apk
          tag: ${{ github.event.release.tag_name }}
          file_glob: true
          overwrite: true
